# Generated by Django 4.0 on 2022-01-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('article', models.TextField()),
                ('image', models.ImageField(default='', upload_to='photos/')),
                ('date_written', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
