# Generated by Django 4.0 on 2022-01-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
