# Generated by Django 4.0 on 2022-01-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
    ]
