# Generated by Django 4.0 on 2022-01-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music',
            field=models.FileField(default='amari.mp3', upload_to='music/'),
        ),
    ]
